# Generated by Django 4.2.6 on 2023-12-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
